server {
    listen 80;

    root /usr/share/nginx/html;

    location = / {
        return 302 /amostrando/;
    }

    location /amostrando/ {
        index index.html;
        try_files $uri $uri/ /amostrando/index.html;
    }

    location /avelite/ {
        index aveLite.html;
        try_files $uri $uri/ /avalite/index.html;
    }
}